// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import ()

type Email struct {
	ID          int64
	Date        string
	Recipient   string
	Sender      string
	Subject     string
	Description string
}

type Feed struct {
	ID   string
	Name string
}

type FeedItem struct {
	ID      string
	Name    string
	FeedID  string
	Subject string
	Body    string
	Date    string
}
